name: PHPStan

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Composer
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHPStan
      run: vendor/bin/phpstan analyse
